"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import BrandLogo from "@/components/BrandLogo";
import Me2uIcon from "@/components/Me2uIcon";
import NotificationBell from "@/components/NotificationBell";
import ShareTemplatesModal from "@/components/referrals/ShareTemplatesModal";
import { authorizedFetch } from "@/lib/fetch";
import { useStore } from "@/lib/store";

type Stats = { total_referrals: number; total_earned: number };
type Referral = { referee_id: string; referee_name: string; pending_rewards: string; referee_kyc_verified: boolean };
type Challenge = { current: number; target: number; reward: number; completed: boolean; week_end: string };
type Milestone = { type: string; referralCount: number; rewardAmount: number; badgeAwarded: string | null; achieved: boolean; progress: number };
type Leader = { user_id: string; username: string; verified_referral_count: number; rank: number; prizeAmount: number | null; is_current_user: boolean };

export default function ReferralsPage() {
  const user = useStore((s) => s.user); const authenticated = useStore((s) => s.isAuthenticated); const authLoading = useStore((s) => s.isLoading); const router = useRouter();
  const [stats, setStats] = useState<Stats | null>(null); const [referrals, setReferrals] = useState<Referral[]>([]); const [challenge, setChallenge] = useState<Challenge | null>(null); const [milestones, setMilestones] = useState<Milestone[]>([]); const [leaders, setLeaders] = useState<Leader[]>([]); const [loading, setLoading] = useState(true); const [copied, setCopied] = useState(false); const [showDetails, setShowDetails] = useState(false); const [showShare, setShowShare] = useState(false);
  const [link, setLink] = useState("");
  useEffect(() => setLink(`${window.location.origin}/r/${user?.username || "XXXX"}`), [user?.username]);
  useEffect(() => { if (!authLoading && !authenticated) router.push("/login"); }, [authLoading, authenticated, router]);
  useEffect(() => { if (!authenticated) return; Promise.all([authorizedFetch("/api/referrals"), authorizedFetch("/api/referrals/challenges"), authorizedFetch("/api/referrals/milestones"), authorizedFetch("/api/referrals/leaderboard?period=current")]).then(async ([a,b,c,d]) => { if(a.ok){const x=await a.json(); setStats(x.stats); setReferrals(x.referrals || []);} if(b.ok) setChallenge((await b.json()).current); if(c.ok) setMilestones((await c.json()).milestones || []); if(d.ok) setLeaders(((await d.json()).leaderboard || []).slice(0,10)); }).catch(() => toast.error("Unable to load referral data. Please try again.")).finally(() => setLoading(false)); }, [authenticated]);
  async function copy() { try { await navigator.clipboard.writeText(link); setCopied(true); toast.success("Link copied!"); setTimeout(() => setCopied(false), 2000); } catch { toast.error("Please copy the link manually."); } }
  async function share() { if (navigator.share) { try { await navigator.share({ title: "Join me on Me2U", text: "Sign up using my referral link!", url: link }); } catch {} } else copy(); }
  if (loading) return <div className="reference-page grid min-h-screen place-items-center"><div className="h-9 w-9 animate-spin rounded-full border-4 border-emerald-600 border-t-transparent" aria-label="Loading referrals" /></div>;
  if (!authenticated && !authLoading) return null;
  const unlockRemaining = Math.max(0, 10 - (user?.verifiedReferralCount || 0));
  return <main className="reference-page app-mobile-screen mx-auto w-full max-w-md overflow-x-hidden px-4 pt-[calc(1.25rem+env(safe-area-inset-top))] md:max-w-5xl md:px-8 md:py-12">
    <header className="mb-5 flex items-start justify-between"><BrandLogo src="/me2u_nav_logo.svg" className="reference-logo" /><div className="flex items-center gap-3"><NotificationBell /><span className="grid h-12 w-12 place-items-center rounded-full bg-emerald-600 font-black text-white">{(user?.name || "Me").slice(0,2).toUpperCase()}</span></div></header>
    <section className="reference-hero relative mb-5 min-h-[31rem] p-6"><p className="text-xs font-bold tracking-[.35em] text-white/80">REFER & EARN</p><h1 className="mt-5 max-w-[17rem] text-5xl font-black leading-[.96]">Invite friends.<br/>Earn rewards.</h1><p className="mt-4 max-w-[18rem] text-xl leading-snug text-white/90">Share your referral link and get ₦1,500 for every verified referral.</p><div aria-hidden="true" className="reference-gift bottom-[9rem] right-[-1.2rem] rotate-6" /><span aria-hidden="true" className="reference-art-coin right-28 top-12 h-12 w-12 rotate-12 text-lg">₦</span><span aria-hidden="true" className="reference-art-coin right-8 top-24 h-9 w-9 -rotate-12 text-sm">₦</span><div className="absolute bottom-5 left-5 right-5 rounded-[1.6rem] bg-white p-4 text-slate-950 shadow-xl"><p className="font-bold">Your Referral Link</p><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 truncate rounded-xl bg-slate-100 px-3 py-3 text-sm">{link}</code><button onClick={copy} aria-label="Copy referral link" className="grid h-11 w-11 place-items-center rounded-xl border border-slate-200 hover:bg-slate-100"><Me2uIcon name={copied ? "check" : "copy"} size={21} /></button><button onClick={share} className="rounded-xl bg-emerald-600 px-4 font-bold text-white hover:bg-emerald-700">Share</button></div>{!user?.accountUnlocked && unlockRemaining > 0 && <button onClick={() => setShowDetails(true)} className="mt-3 flex w-full items-center gap-2 rounded-xl bg-amber-50 p-3 text-left text-sm text-amber-800 hover:bg-amber-100"><span aria-hidden="true">👑</span><span className="min-w-0"><b className="block">{unlockRemaining} more verified referrals to unlock withdrawals</b><small>Or pay ₦2,000 one-time fee to unlock instantly</small></span><span className="ml-auto text-2xl">›</span></button>}</div></section>
    <section className="mb-6 grid grid-cols-4 gap-2"><Stat label="Invited" value={stats?.total_referrals || 0} icon="referral" /><Stat label="Verified" value={user?.verifiedReferralCount || 0} icon="check" /><Stat label="Earned" value={`₦${(stats?.total_earned || 0).toLocaleString()}`} icon="moneyBag" /><Stat label="Potential" value={`₦${((stats?.total_referrals || 0) * 2500).toLocaleString()}`} icon="market" /></section>
    <section className="reference-card mb-5 p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-3xl font-black text-slate-950">How It Works</h2><button onClick={() => setShowDetails(!showDetails)} aria-expanded={showDetails} className="rounded-full border border-slate-200 px-4 py-2 text-sm font-bold hover:bg-slate-50">{showDetails ? "Hide Details" : "View Details"} →</button></div><div className="mt-6 grid grid-cols-4 gap-2">{[["referral","Friend signs up"],["check","They verify"],["moneyBag","You earn"],["wallet","Withdraw"]].map(([icon,label], index) => <div key={label} className="min-w-0 text-center"><span className="reference-icon mx-auto h-12 w-12"><Me2uIcon name={icon as any} size={22} /></span><span className="mx-auto mt-2 grid h-6 w-6 place-items-center rounded-full bg-emerald-600 text-xs font-bold text-white">{index+1}</span><b className="mt-1 block text-xs text-slate-950">{label}</b></div>)}</div><div className="mt-5 rounded-2xl bg-emerald-50 p-4"><b className="text-slate-950">Refer top performers earn more!</b><p className="text-sm text-slate-500">The more you refer, the higher your rewards.</p></div></section>
    {showDetails && <section className="reference-card mb-5 p-5" aria-label="Referral details"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black text-slate-950">Referral Details</h2><button onClick={() => setShowShare(true)} className="rounded-full bg-emerald-600 px-4 py-2 text-sm font-bold text-white">Share Templates</button></div>{challenge && <div className="mb-4 rounded-2xl bg-orange-50 p-4"><b>Weekly Challenge</b><p className="mt-1 text-sm text-slate-600">{challenge.current} / {challenge.target} verified · Win ₦{challenge.reward.toLocaleString()}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-orange-100"><div className="h-full bg-orange-500" style={{width:`${Math.min(100, challenge.current / challenge.target * 100)}%`}} /></div></div>}<div className="grid gap-3 sm:grid-cols-2">{milestones.map((item) => <div key={item.type} className="rounded-2xl border border-slate-100 p-4"><b>{item.referralCount} Referrals</b><p className="text-sm text-slate-500">₦{item.rewardAmount.toLocaleString()} + {item.badgeAwarded || "reward"}</p><p className="mt-2 text-xs font-bold text-emerald-700">{item.achieved ? "Achieved" : `${item.progress}% complete`}</p></div>)}</div><h3 className="mt-6 font-black text-slate-950">Your Referrals</h3>{referrals.length ? <div className="mt-2 divide-y divide-slate-100">{referrals.map((ref) => <div key={ref.referee_id} className="py-3"><b className="block text-slate-950">{ref.referee_name}</b><small className="text-slate-500">{ref.pending_rewards} · {ref.referee_kyc_verified ? "Verified" : "Pending KYC"}</small></div>)}</div> : <p className="mt-2 text-sm text-slate-500">No referrals yet. Share your link to get started.</p>}<h3 className="mt-6 font-black text-slate-950">Leaderboard</h3><div className="mt-2 divide-y divide-slate-100">{leaders.map((entry) => <div key={entry.user_id} className="flex items-center justify-between py-3"><span><b>#{entry.rank} {entry.is_current_user ? "You" : entry.username}</b><small className="ml-2 text-slate-500">{entry.verified_referral_count} verified</small></span><b className="text-emerald-700">{entry.prizeAmount ? `₦${entry.prizeAmount.toLocaleString()}` : ""}</b></div>)}</div></section>}
    {showShare && user?.username && <ShareTemplatesModal isOpen onClose={() => setShowShare(false)} referralLink={link} username={user.username} />}
  </main>;
}

function Stat({label,value,icon}:{label:string;value:string|number;icon:string}) { return <div className="reference-card min-w-0 p-3"><span className="text-emerald-600"><Me2uIcon name={icon as any} size={20}/></span><b className="mt-3 block truncate text-2xl text-slate-950 tabular-nums">{value}</b><small className="block text-slate-500">{label}</small></div>; }
