"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import BrandLogo from "@/components/BrandLogo";
import Me2uIcon, { type Me2uIconName } from "@/components/Me2uIcon";
import NotificationBell from "@/components/NotificationBell";
import { useStore } from "@/lib/store";
import { getCreditLevel, getTrustScoreBreakdown } from "@/lib/product-features";

const primaryActions: Array<{ label: string; detail: string; path: string; icon: Me2uIconName; tone: string }> = [
  { label: "Market", detail: "Buy & sell", path: "/marketplace", icon: "market", tone: "reference-icon" },
  { label: "Loans", detail: "Get funds", path: "/loans", icon: "loans", tone: "reference-icon reference-icon-lime" },
  { label: "KYC", detail: "Verify identity", path: "/kyc", icon: "shield", tone: "reference-icon" },
];
const shortcuts: Array<{ label: string; detail: string; path: string; icon: Me2uIconName }> = [
  { label: "Savings", detail: "Grow your money", path: "/savings", icon: "savings" }, { label: "Circles", detail: "Save together", path: "/circles", icon: "group" }, { label: "Deals", detail: "Exclusive offers", path: "/deals", icon: "deal" }, { label: "Refer", detail: "Invite & earn", path: "/referrals", icon: "referral" }, { label: "Learn", detail: "Build knowledge", path: "/learn", icon: "book" }, { label: "Secure", detail: "Stay protected", path: "/security", icon: "security" },
];

export default function Dashboard() {
  const user = useStore((s) => s.user); const transactions = useStore((s) => s.transactions); const activeLoans = useStore((s) => s.activeLoans); const authenticated = useStore((s) => s.isAuthenticated); const loading = useStore((s) => s.isLoading); const router = useRouter();
  const [mounted, setMounted] = useState(false); const [showBalance, setShowBalance] = useState(true);
  useEffect(() => setMounted(true), []); useEffect(() => { if (mounted && !loading && !authenticated) router.push("/login"); }, [authenticated, loading, mounted, router]);
  if (!mounted || (!authenticated && !loading)) return null;
  const firstName = user?.name?.trim().split(/\s+/)[0] || "Friend"; const username = user?.username || firstName.toLowerCase(); const level = getCreditLevel(user?.trustScore || 0); const nextSteps = getTrustScoreBreakdown(user, transactions, activeLoans).slice(0, 2); const balance = user?.balance || 0; const bankReady = Boolean(user?.bankName && user.accountNumber);
  return <main className="reference-page app-mobile-screen mx-auto w-full max-w-md overflow-x-hidden px-4 pt-[calc(1.25rem+env(safe-area-inset-top))] md:max-w-6xl md:px-8 md:py-12">
    <header className="mb-5 flex items-start justify-between gap-3"><div className="min-w-0"><BrandLogo src="/me2u_nav_logo.svg" className="reference-logo" /><p className="mt-0.5 text-xs font-medium text-[var(--color-text-secondary)]">People · Opportunities · Growth</p></div><NotificationBell /></header>
    <section className="mb-5 flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="grid h-[4.6rem] w-[4.6rem] shrink-0 place-items-center rounded-full border-8 border-emerald-100 bg-emerald-200 text-2xl font-black text-emerald-900">{firstName.slice(0, 2).toUpperCase()}</div><div className="min-w-0"><p className="text-lg font-medium text-slate-500">Welcome</p><h1 className="truncate text-[1.7rem] font-black text-slate-950">@{username}</h1><p className="text-base text-slate-500">Good to see you again!</p></div></div><div className="hidden rounded-full bg-emerald-100 px-4 py-3 text-sm font-bold text-emerald-900 sm:flex sm:items-center sm:gap-2"><span aria-hidden="true">🌱</span> Smarter Money Together</div></section>
    <section className="reference-hero mb-5 p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xl font-bold">Main Balance</p><div className="mt-2 flex items-center gap-3"><p className="text-5xl font-black tracking-tight tabular-nums">{showBalance ? `₦${balance.toLocaleString()}` : "₦••••••"}</p><button type="button" aria-label={showBalance ? "Hide balance" : "Show balance"} onClick={() => setShowBalance(!showBalance)} className="grid h-11 w-11 place-items-center rounded-full bg-white/15 hover:bg-white/25"><Me2uIcon name={showBalance ? "visible" : "invisible"} size={23} /></button></div><p className="mt-1 text-base text-white/80">Your wallet, more possibilities.</p></div>{!bankReady && <button onClick={() => router.push("/profile")} className="rounded-full bg-amber-50 px-3 py-2 text-left text-xs font-bold text-amber-900 hover:bg-white sm:px-4 sm:text-sm">⚠ Verify to add bank <span aria-hidden="true">›</span></button>}</div><div className="mt-5 grid grid-cols-2 gap-3"><button onClick={() => router.push("/wallet")} className="flex min-h-[5.8rem] items-center gap-3 rounded-[1.5rem] bg-white px-4 text-left text-slate-950 transition-transform hover:-translate-y-0.5"><span className="reference-icon"><Me2uIcon name="cash" size={25} /></span><span><b className="block text-xl">Receive</b><small className="text-sm text-slate-500">Get paid to your wallet</small></span></button><button onClick={() => router.push("/withdraw")} className="flex min-h-[5.8rem] items-center gap-3 rounded-[1.5rem] bg-lime-400 px-4 text-left text-emerald-950 transition-transform hover:-translate-y-0.5"><span className="grid h-11 w-11 place-items-center rounded-full bg-white/75"><Me2uIcon name="requestMoney" size={25} /></span><span><b className="block text-xl">Withdraw</b><small className="text-sm">Send to your bank</small></span></button></div></section>
    <section className="mb-5 grid grid-cols-3 gap-3">{primaryActions.map((item) => <button key={item.label} onClick={() => router.push(item.path)} className="reference-card min-w-0 p-4 text-left transition-transform hover:-translate-y-0.5"><span className={item.tone}><Me2uIcon name={item.icon} size={24} /></span><b className="mt-3 block text-lg text-slate-950">{item.label}</b><small className="block text-sm text-slate-500">{item.detail}</small></button>)}</section>
    <section className="reference-card mb-5 grid grid-cols-3 overflow-hidden p-2">{shortcuts.map((item, i) => <button key={item.label} onClick={() => router.push(item.path)} className={`min-w-0 px-1 py-4 text-center hover:bg-emerald-50 ${i > 2 ? "border-t border-slate-100" : ""} ${i % 3 ? "border-l border-slate-100" : ""}`}><span className="reference-icon mx-auto h-11 w-11"><Me2uIcon name={item.icon} size={21} /></span><b className="mt-2 block text-sm text-slate-950">{item.label}</b><small className="block truncate text-xs text-slate-500">{item.detail}</small></button>)}</section>
    <section className="reference-card p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-2xl font-black text-slate-950">Me2U Trust Score</h2><p className="mt-1 font-semibold text-slate-800">{level.name} level · {level.next}</p><p className="mt-1 text-sm text-slate-500">Complete more steps to unlock higher benefits.</p></div><div className="grid h-24 w-24 shrink-0 place-items-center rounded-full border-[10px] border-emerald-400 bg-white text-center"><b className="text-3xl text-emerald-800">{user?.trustScore || 0}</b><small className="-mt-5 text-slate-400">/ 100</small></div></div><div className="mt-5"><div className="mb-2 flex items-center justify-between"><h3 className="font-bold text-slate-950">Next steps</h3><button onClick={() => router.push("/profile")} className="font-bold text-emerald-700">See all ›</button></div>{nextSteps.map((step) => <button key={step.label} onClick={() => router.push("/profile")} className="reference-row w-full text-left"><span className="reference-icon h-11 w-11"><Me2uIcon name="shield" size={20} /></span><span className="min-w-0"><b className="block text-slate-950">{step.label}</b><small className="block truncate text-slate-500">{step.detail}</small></span><span className="reference-chevron">›</span></button>)}</div></section>
  </main>;
}
